name: HideAndSeek
version: '${project.version}'
main: cz.ragy.hideandseek.HideAndSeek
api-version: 1.19
authors: [ Radekminecraft, FungY911 ]
description: Basic and simple hide and seek plugin from Ragy dev crew

depend:
  - PlaceholderAPI
commands:
  has:
    usage: /has
    description: Main command for plugin
